#54: added support for passing object as value
dance2die/react-use-localstorage pull request #55
Opened 2021-10-30 22:34 UTC by fkrafi

2021-10-30 23:42 UTC, TheAifam5 commented
In this StackBlitz example, I've made a playground around mutable and immutable objects
https://stackblitz.com/edit/react-ts-gi66ra?file=index.tsx

The first one, if the value is not saved in localStorage, the view does not get updated and only one last character is stored (in this example, initial + the last entered character) in localStorage.

The other ones works well with mutable and immutable objects.

Could you check that one too why does it happen?

2021-10-30 23:45 UTC, TheAifam5 requested changes

2021-10-30 23:45 UTC, TheAifam5 commented on src/index.ts
> +): [string | object, Dispatch<string | object>] {
Rather an string or an pure object, what do you thing about adding generic parameter type, like returning T, where T extends from an object?

2021-10-30 23:45 UTC, TheAifam5 commented on src/index.ts
> +  return value ? (value.startsWith('{') ? JSON.parse(value) : value) : null;
Identifying based on first character is not a best approach, user may store some arbitrary data starting with that character, like format string. Whats the fallback scenario when it starts with { but does not end (invalid json object)?

2021-10-30 23:45 UTC, TheAifam5 commented on src/index.ts
> +      typeof newValue === 'string' ? newValue : JSON.stringify(newValue)
If the string is created using "new String('value')", the condition will fail. You can add additional check using "instanceof" or use different approach:

Object.prototype.toString.call(newValue) == '[object String]'

Additionally, "null" and "undefined" will also fail I think.

2021-10-30 23:45 UTC, TheAifam5 commented on test/index.test.ts
> +      localStorage.removeItem(KEY);
You can move this to "beforeEach" scope.

2021-10-30 23:45 UTC, TheAifam5 commented on test/index.test.ts
> +    CHANGED: { key1: 'value1', key2: 'value2' },
This is unused / test is missing.

2021-10-31 05:45 UTC, fkrafi commented on src/index.ts
> +  return value ? (value.startsWith('{') ? JSON.parse(value) : value) : null;
can i use `lodash` package

2021-10-31 19:56 UTC, fkrafi commented
@TheAifam5 , i have changed all the reviews from your comments, can you please verify?

2022-01-03 21:13 UTC, closed without merging